export const RESTORE_SETTINGS = "RESTORE_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
//
export const APPEND_DOWNLOAD_HISTORY = "APPEND_DOWNLOAD_HISTORY";
export const DELETE_DOWNLOAD_HISTORY = "DELETE_DOWNLOAD_HISTORY";
export const UPDATE_DOWNLOAD_HISTORY = "UPDATE_DOWNLOAD_HISTORY";
export const CLEAR_DOWNLOAD_HISTORY = "CLEAR_DOWNLOAD_HISTORY";
